volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: karramb/kozhev
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - db

  gateway:
    image: karramb/kozhev_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - 8000:80
    depends_on:
      - db
      - backend